name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    name: Build & Test (${{ matrix.os }}, ${{ matrix.rust.VERSION }}), ${{ matrix.rust.FLAGS }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust:
          - VERSION: stable
            FLAGS: ""
          - VERSION: 1.56.0
            FLAGS: ""
          - VERSION: nightly
            FLAGS: ""
          - VERSION: nightly
            FLAGS: "-Z direct-minimal-versions"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust (${{ matrix.rust.VERSION }})
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust.VERSION }}

      - run: cargo check --workspace --tests ${{ matrix.rust.FLAGS }}

      - run: cargo test --workspace ${{ matrix.rust.FLAGS }}
